---
title: "Assignment_10_clustering"
author: "Sunil S"
date: "14 October 2017"
output: html_document
---
## Clear environment and load IRIS data set
```{r setup, include=FALSE}
rm(list=ls(all=T))

library(datasets)

set.seed(7568)
data = iris
summary(data)


```

##Preprocessing the data
```{r}
sum(is.na(data))

#Check for categorical attrubutes
str(data)

species = as.list(data$Species)
species = unlist(species)
data = data[1:4]
```

##Data exploration
```{r, include=F,echo=T}
#Visualizing distance between observations
library(factoextra)
distance = get_dist(data)

# Plot a visual representation of the inter-observation distances
fviz_dist(distance, gradient = list(low = "#00AFBB", mid = "white", high = "#FC4E07"))

```
## Hierarchial clustering
```{r, echo=T,include = T}
#converting data in the form of distance matrix

iris_dist = dist(data, method = "euclidean")
model_1 = hclust(iris_dist, method = "single")
plot(model_1)
rect.hclust(model_1, k = 6, border = "red")
model_1_cut = cutree(model_1, 2)
table(iris$Species, model_1_cut)

iris_dist = dist(data, method = "manhattan")
model_2 = hclust(iris_dist,method = "average")
plot(model_2)
rect.hclust(model_2, k = 6, border = "blue")
model_1_cut = cutree(model_2, h=3)
table(iris$Species, model_1_cut)

iris_dist = dist(data, method = "maximum")
model_3 = hclust(iris_dist,method = "average" )
plot(model_3)
rect.hclust(model_3, k = 6, border = "orange")
model_1_cut = cutree(model_3, h=1.5)
table(iris$Species, model_1_cut)

```
